######
# Configure remote sshd container connexion
######

- name: Configure remote sshd container connexion
  hosts: coos
  remote_user: root
  gather_facts: yes
  tasks:

  - name: Change ssh port to 2222
    when: inventory_hostname in groups['coos']
    set_fact:
      ansible_port: 2222