######
# Install and configure traefik proxy
######

- name: Change ssh port to 2222
  when: inventory_hostname in groups['coos']
  set_fact:
    ansible_port: 2222

- name: Create web network
  docker_network:
    name: webnet

- name: Create config folder
  file:
    path: /host/var/docker-peristant-sto/traefik
    state: directory

- name: Copy traefik config
  ansible.builtin.copy:
    src: traefik.yml
    dest: /host/var/docker-peristant-sto/traefik/traefik.yml

- name: Start traefik as server
  docker_container:
    name: proxy
    image: traefik
    restart_policy: unless-stopped
    networks:
    - name: webnet
    volumes:
      - /var/docker-peristant-sto/traefik/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    published_ports:
      - 80:80
      - 443:443

- name: Change ssh port to 22
  when: inventory_hostname in groups['coos']
  set_fact:
    ansible_port: 22