######
# Install vault in coos
######

- name: Create vault folder
  file:
    path: /host/var/docker-peristant-sto/vault
    state: directory

- name: Create vault config folder
  file:
    path: /host/var/docker-peristant-sto/vault/config
    state: directory

- name: Ensure group "vault" exists with correct gid
  group:
    name: vault
    state: present
    gid: 1000

- name: Create vault data folder
  file:
    path: /host/var/docker-peristant-sto/vault/data
    state: directory
    mode: 775
    group: vault

- name: Copy vault config
  ansible.builtin.copy:
    src: vault_config.hcl
    dest: /host/var/docker-peristant-sto/vault/config/vault_config.hcl

- name: Start vault as server
  docker_container:
    name: vault
    image: vault
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.vault.rule: Host(`vault.lab.blocker.rocks`)
      traefik.http.services.vault.loadbalancer.server.port: "8200"
      traefik.http.routers.vault.entrypoints: websecure
      traefik.docker.network: webnet
      traefik.http.routers.vault.tls: "true"
      traefik.http.routers.vault.tls.certresolver: letsencrypt
    command: "server -config /config/vault_config.hcl"
    capabilities:
      - "IPC_LOCK"
    networks:
      - name: webnet
    volumes:
      - /var/docker-peristant-sto/vault/data/:/data
      - /var/docker-peristant-sto/vault/config/:/config
