######
# Install bitwarden in coos
######

- name: Install and configure bitwarden
  hosts: bitwarden
  remote_user: root
  gather_facts: yes
  tasks:

  - name: Change ssh port to 2222
    when: inventory_hostname in groups['coos']
    set_fact:
      ansible_port: 2222

  - name: Create web network
    remote_user: dev
    become: yes
    docker_network:
      name: webnet

  - name: Copy traefik config
    remote_user: dev
    become: yes
    ansible.builtin.copy:
      src: ressources/traefik.yml
      dest: /host/var/traefik/traefik.yml

  - name: Start traefik as server
    when: inventory_hostname in groups['coos']
    remote_user: dev
    become: yes
    docker_container:
      name: proxy
      image: traefik
      networks:
      - name: webnet
      volumes:
        - /var/traefik/:/etc/traefik/
        - /var/run/docker.sock:/var/run/docker.sock
      published_ports:
        - 80:80
        - 443:443

  - name: Start bitwarden as server
    when: inventory_hostname in groups['coos']
    remote_user: dev
    become: yes
    docker_container:
      name: bitwarden
      image: bitwardenrs/server:latest
      labels:
        traefik.enable: "true"
        traefik.http.routers.bitwarden.rule: Host(`bitwarden.lab.blocker.rocks`)
        traefik.http.services.bitwarden.loadbalancer.server.port: 443
        traefik.docker.network: webnet
      networks:
      - name: webnet
      volumes:
        - /var/docker-peristant-sto/bitwarden/data/:/data
      published_ports:
        - 80:80
        - 443:443