######
# Install consul on ubuntu
# Adapted from Hashicorp's official documentation: 
#   https://learn.hashicorp.com/tutorials/consul/get-started-install?in=consul/getting-started
######

- name: Install and configure
  hosts: consul-slave
  remote_user: root

  tasks:

  - name: Add HashiCorp’s official GPG key
    when: inventory_hostname not in groups['coos']
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
    become: yes

  - name: Add HashiCorp's Repository
    when: inventory_hostname not in groups['coos']
    apt_repository:
    # Small magic trick here, using ansible fact's to get ubuntu's version "nickname"
      repo: deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
      state: present
    become: yes

  - name: Update and install consul
    when: inventory_hostname not in groups['coos']
    apt:
      name:
        - consul
      state: latest
      update_cache: yes
    become: yes

  - name: Start consul as server
    when: inventory_hostname in groups['coos']
    ansible.builtin.command:
      argv:
        - docker run
        - -d
        - -p 8500:8500
        - -p 8600:8600/udp
        - consul agent
        - -server
        - -ui
        - -bootstrap-expect=1
