######
# Install consul on ubuntu
# Adapted from Hashicorp's official documentation: 
#   https://learn.hashicorp.com/tutorials/consul/get-started-install?in=consul/getting-started
######

- name: Install and configure
  hosts: consul-slave
  remote_user: root
  gather_facts: yes
  tasks:

  - name: Add HashiCorp’s official GPG key
    when: inventory_hostname not in groups['coos']
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
    become: yes

  - name: Add HashiCorp's Repository
    when: inventory_hostname not in groups['coos']
    apt_repository:
    # Small magic trick here, using ansible fact's to get ubuntu's version "nickname"
      repo: deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
      state: present
    become: yes

  - name: Update and install consul
    when: inventory_hostname not in groups['coos']
    apt:
      name:
        - consul
      state: latest
      update_cache: yes
    become: yes

  - name: Get hostname
    shell: hostname
    register: hostname

  - set_fact:
      hostname: "{{ hostname.stdout }}"

  - name: Change ssh port to 2222
    when: inventory_hostname in groups['coos']
    set_fact:
      ansible_port: 2222

  - name: Start consul as server
    when: inventory_hostname in groups['coos']
    remote_user: dev
    become: yes
    docker_container:
      name: consul-agent
      image: consul
      ports:
        - 8500:8500
        - 8600:8600/udp
      command: agent -node {{ ansible_facts["hostname"] }} -enable-script-checks=true  -data-dir=/tmp/consul

  - name: Execute consul join
    when: inventory_hostname in groups['coos']
    become: yes
    remote_user: dev
    community.docker.docker_container_exec:
      container: consul-agent 
      command: consul join control-command