######
# Install bitwarden in coos
######

- name: Start bitwarden as server
  when: inventory_hostname in groups['coos']
  docker_container:
    name: bitwarden
    image: bitwardenrs/server:latest
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.bitwarden.rule: Host(`bitwarden.lab.blocker.rocks`)
      traefik.http.services.bitwarden.loadbalancer.server.port: "80"
      traefik.http.routers.bitwarden.entrypoints: websecure
      traefik.docker.network: webnet
      traefik.http.routers.bitwarden.tls: "true"
      traefik.http.routers.bitwarden.tls.certresolver: letsencrypt
    networks:
    - name: webnet
    volumes:
      - /var/docker-peristant-sto/bitwarden/data/:/data